AWSTemplateFormatVersion: '2010-09-09'
Description:  This template creates a customized AWS Systems Manager document with steps for Windows and Linux to download the CloudWatch configuration files from an S3 bucket accessible by AWS Organizations accounts to the CloudWatch configuration directory and then start / stop the agent on the instance in order to apply configuration changes.
Parameters:
  CloudWatchAgentInstallAndConfigureDocumentName:
    Description: Specify the name of the CloudWatch Install and Configure Document.
    Type: String
    Default:  SSMQuickSetupCloudWatchAgentInstallAndConfigure

Resources:
  installDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: !Ref CloudWatchAgentInstallAndConfigureDocumentName
      Content:
        schemaVersion: "2.2"
        description: "A composite document for installing and configuring the CloudWatch Agent."
        parameters:
          sourceInfoWindows:
            description: "Amazon S3 bucket used to store CloudWatch configuration files"
            type: StringMap
            "displayType": "textarea"
            default:
              path: !Sub "https://s3.amazonaws.com/amazon-cloudwatch-config-${AWS::AccountId}/config/standard/windows/"
          sourceInfoLinux:
            description: "Amazon S3 bucket used to store CloudWatch configuration files"
            type: StringMap
            "displayType": "textarea"
            default:
              path: !Sub "https://s3.amazonaws.com/amazon-cloudwatch-config-${AWS::AccountId}/config/standard/linux/"
        mainSteps:
          - action: "aws:runDocument"
            name: "installCWAgent"
            inputs:
              documentType: "SSMDocument"
              documentPath: "AWS-ConfigureAWSPackage"
              documentParameters:
                action:  Install
                name: AmazonCloudWatchAgent
          - action: aws:downloadContent
            precondition:
              StringEquals:
                - platformType
                - Windows
            name: downloadStandardCloudWatchConfigWindows
            inputs:
              sourceType: S3
              sourceInfo: "{{ sourceInfoWindows }}"
              destinationPath: "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Configs"
          - action: aws:runPowerShellScript
            precondition:
              StringEquals:
                - platformType
                - Windows
            name: runShellScript
            inputs:
              timeoutSeconds: '60'
              runCommand:
                - del /f C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Configs\\*.etag
          - action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Windows
            name: "StopCloudWatchWindows"
            inputs:
              documentType: "SSMDocument"
              documentPath: "AmazonCloudWatch-ManageAgent"
              documentParameters:
                action: "stop"
                mode: "ec2"
          - action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Windows
            name: "StartCloudWatchWindows"
            inputs:
              documentType: "SSMDocument"
              documentPath: "AmazonCloudWatch-ManageAgent"
              documentParameters:
                action: "start"
                mode: "ec2"
          - action: aws:downloadContent
            precondition:
              StringEquals:
                - platformType
                - Linux
            name: downloadStandardCloudWatchConfigLinux
            inputs:
              sourceType: S3
              sourceInfo: "{{ sourceInfoLinux }}"
              destinationPath: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d"
          - action: aws:runShellScript
            precondition:
              StringEquals:
                - platformType
                - Linux
            name: runShellScript
            inputs:
              timeoutSeconds: '60'
              runCommand:
                - rm -f /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/*.etag
          - action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Linux
            name: "StopCloudWatchLinux"
            inputs:
              documentType: "SSMDocument"
              documentPath: "AmazonCloudWatch-ManageAgent"
              documentParameters:
                action: "stop"
                mode: "ec2"
          - action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Linux
            name: "StartCloudWatchLinux"
            inputs:
              documentType: "SSMDocument"
              documentPath: "AmazonCloudWatch-ManageAgent"
              documentParameters:
                action: "start"
                mode: "ec2"
